// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(agicash_ffiFFI)
import agicash_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_agicash_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_agicash_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureAgicashFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol AgicashWalletProtocol: AnyObject, Sendable {
    
    /**
     * Register an anonymous guest account against OpenSecret. Generates a
     * throwaway password (the user never sees it) and returns the resulting
     * `Session` so the Swift consumer can persist the refresh token.
     */
    func authGuest() async throws  -> Session
    
    /**
     * Email + password login.
     */
    func authLogin(email: String, password: String) async throws  -> Session
    
    /**
     * Best-effort server logout. Always clears the in-memory session even
     * if the server-side call fails (e.g. expired token, network error).
     * The Swift consumer should also drop its Keychain entry on success.
     */
    func authLogout() async throws 
    
    /**
     * Return whether the wallet currently holds a session.
     */
    func authStatus() async throws  -> AuthStatus
    
    /**
     * Return the currently-loaded session, or `None` if the wallet is
     * logged out. Lets the Swift consumer re-sync its Keychain copy after
     * a `auth_guest` / `auth_login` call.
     */
    func getPersistedSession() async  -> Session?
    
    /**
     * List Supabase `wallet.accounts` rows for the currently-logged-in
     * user. Phase 1 maps each row through `AccountFfi::from(Account)` which
     * hard-codes `balance: "0"` and `unit: ""` — actual balance wiring
     * arrives in Phase 2 once the proofs layer is exposed.
     */
    func listAccounts() async throws  -> [AccountFfi]
    
    /**
     * Rehydrate an existing session into the wallet. Called by the Swift
     * consumer on app launch after reading the refresh token from Keychain.
     * Performs an OpenSecret token refresh so the internal client has a
     * fresh access token. On refresh failure the in-memory session is
     * cleared and an `Auth` error is returned so the consumer can drop the
     * Keychain entry.
     */
    func setSession(userIdUuid: String, refreshToken: String) async throws 
    
}
open class AgicashWallet: AgicashWalletProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_agicash_ffi_fn_clone_agicashwallet(self.handle, $0) }
    }
    /**
     * Build a wallet that talks to the given `OpenSecret` and Supabase
     * endpoints. The `client_id_uuid` must be a stringified UUID identifying
     * this Agicash app to `OpenSecret` (matches the `OPENSECRET_CLIENT_ID`
     * env var used by the CLI).
     */
public convenience init(opensecretUrl: String, opensecretClientIdUuid: String, supabaseUrl: String, supabaseAnonKey: String)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_agicash_ffi_fn_constructor_agicashwallet_new(
        FfiConverterString.lower(opensecretUrl),
        FfiConverterString.lower(opensecretClientIdUuid),
        FfiConverterString.lower(supabaseUrl),
        FfiConverterString.lower(supabaseAnonKey),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_agicash_ffi_fn_free_agicashwallet(handle, $0) }
    }

    

    
    /**
     * Register an anonymous guest account against OpenSecret. Generates a
     * throwaway password (the user never sees it) and returns the resulting
     * `Session` so the Swift consumer can persist the refresh token.
     */
open func authGuest()async throws  -> Session  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_agicash_ffi_fn_method_agicashwallet_auth_guest(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_agicash_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_agicash_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_agicash_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeSession_lift,
            errorHandler: FfiConverterTypeFfiError_lift
        )
}
    
    /**
     * Email + password login.
     */
open func authLogin(email: String, password: String)async throws  -> Session  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_agicash_ffi_fn_method_agicashwallet_auth_login(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(email),FfiConverterString.lower(password)
                )
            },
            pollFunc: ffi_agicash_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_agicash_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_agicash_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeSession_lift,
            errorHandler: FfiConverterTypeFfiError_lift
        )
}
    
    /**
     * Best-effort server logout. Always clears the in-memory session even
     * if the server-side call fails (e.g. expired token, network error).
     * The Swift consumer should also drop its Keychain entry on success.
     */
open func authLogout()async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_agicash_ffi_fn_method_agicashwallet_auth_logout(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_agicash_ffi_rust_future_poll_void,
            completeFunc: ffi_agicash_ffi_rust_future_complete_void,
            freeFunc: ffi_agicash_ffi_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeFfiError_lift
        )
}
    
    /**
     * Return whether the wallet currently holds a session.
     */
open func authStatus()async throws  -> AuthStatus  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_agicash_ffi_fn_method_agicashwallet_auth_status(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_agicash_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_agicash_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_agicash_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeAuthStatus_lift,
            errorHandler: FfiConverterTypeFfiError_lift
        )
}
    
    /**
     * Return the currently-loaded session, or `None` if the wallet is
     * logged out. Lets the Swift consumer re-sync its Keychain copy after
     * a `auth_guest` / `auth_login` call.
     */
open func getPersistedSession()async  -> Session?  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_agicash_ffi_fn_method_agicashwallet_get_persisted_session(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_agicash_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_agicash_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_agicash_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterOptionTypeSession.lift,
            errorHandler: nil
            
        )
}
    
    /**
     * List Supabase `wallet.accounts` rows for the currently-logged-in
     * user. Phase 1 maps each row through `AccountFfi::from(Account)` which
     * hard-codes `balance: "0"` and `unit: ""` — actual balance wiring
     * arrives in Phase 2 once the proofs layer is exposed.
     */
open func listAccounts()async throws  -> [AccountFfi]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_agicash_ffi_fn_method_agicashwallet_list_accounts(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_agicash_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_agicash_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_agicash_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeAccountFfi.lift,
            errorHandler: FfiConverterTypeFfiError_lift
        )
}
    
    /**
     * Rehydrate an existing session into the wallet. Called by the Swift
     * consumer on app launch after reading the refresh token from Keychain.
     * Performs an OpenSecret token refresh so the internal client has a
     * fresh access token. On refresh failure the in-memory session is
     * cleared and an `Auth` error is returned so the consumer can drop the
     * Keychain entry.
     */
open func setSession(userIdUuid: String, refreshToken: String)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_agicash_ffi_fn_method_agicashwallet_set_session(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(userIdUuid),FfiConverterString.lower(refreshToken)
                )
            },
            pollFunc: ffi_agicash_ffi_rust_future_poll_void,
            completeFunc: ffi_agicash_ffi_rust_future_complete_void,
            freeFunc: ffi_agicash_ffi_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeFfiError_lift
        )
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAgicashWallet: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = AgicashWallet

    public static func lift(_ handle: UInt64) throws -> AgicashWallet {
        return AgicashWallet(unsafeFromHandle: handle)
    }

    public static func lower(_ value: AgicashWallet) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AgicashWallet {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: AgicashWallet, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAgicashWallet_lift(_ handle: UInt64) throws -> AgicashWallet {
    return try FfiConverterTypeAgicashWallet.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAgicashWallet_lower(_ value: AgicashWallet) -> UInt64 {
    return FfiConverterTypeAgicashWallet.lower(value)
}




public struct AccountFfi: Equatable, Hashable {
    /**
     * Stringified UUID for the account row.
     */
    public var id: String
    public var name: String
    /**
     * One of `"cashu"` or `"spark"` (matches the wire enum on the Rust side).
     */
    public var accountType: String
    /**
     * One of `"BTC"`, `"USD"`, `"USDB"`.
     */
    public var currency: String
    /**
     * Cashu mints set this to the mint URL from `details.mint_url`; Spark
     * accounts return `None`.
     */
    public var mintUrl: String?
    /**
     * Decimal-stringified balance. Phase 1 always returns `"0"` — the
     * underlying wallet layer that tracks proofs/balance arrives in Phase 2+.
     */
    public var balance: String
    /**
     * Sat / cent / usdb sub-unit label. Phase 1 returns an empty string.
     */
    public var unit: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Stringified UUID for the account row.
         */id: String, name: String, 
        /**
         * One of `"cashu"` or `"spark"` (matches the wire enum on the Rust side).
         */accountType: String, 
        /**
         * One of `"BTC"`, `"USD"`, `"USDB"`.
         */currency: String, 
        /**
         * Cashu mints set this to the mint URL from `details.mint_url`; Spark
         * accounts return `None`.
         */mintUrl: String?, 
        /**
         * Decimal-stringified balance. Phase 1 always returns `"0"` — the
         * underlying wallet layer that tracks proofs/balance arrives in Phase 2+.
         */balance: String, 
        /**
         * Sat / cent / usdb sub-unit label. Phase 1 returns an empty string.
         */unit: String) {
        self.id = id
        self.name = name
        self.accountType = accountType
        self.currency = currency
        self.mintUrl = mintUrl
        self.balance = balance
        self.unit = unit
    }

    
}

#if compiler(>=6)
extension AccountFfi: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAccountFfi: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AccountFfi {
        return
            try AccountFfi(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                accountType: FfiConverterString.read(from: &buf), 
                currency: FfiConverterString.read(from: &buf), 
                mintUrl: FfiConverterOptionString.read(from: &buf), 
                balance: FfiConverterString.read(from: &buf), 
                unit: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: AccountFfi, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.accountType, into: &buf)
        FfiConverterString.write(value.currency, into: &buf)
        FfiConverterOptionString.write(value.mintUrl, into: &buf)
        FfiConverterString.write(value.balance, into: &buf)
        FfiConverterString.write(value.unit, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAccountFfi_lift(_ buf: RustBuffer) throws -> AccountFfi {
    return try FfiConverterTypeAccountFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAccountFfi_lower(_ value: AccountFfi) -> RustBuffer {
    return FfiConverterTypeAccountFfi.lower(value)
}


public struct AuthStatus: Equatable, Hashable {
    public var loggedIn: Bool
    /**
     * Stringified user UUID when `logged_in == true`, else None.
     */
    public var userId: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(loggedIn: Bool, 
        /**
         * Stringified user UUID when `logged_in == true`, else None.
         */userId: String?) {
        self.loggedIn = loggedIn
        self.userId = userId
    }

    
}

#if compiler(>=6)
extension AuthStatus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAuthStatus: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AuthStatus {
        return
            try AuthStatus(
                loggedIn: FfiConverterBool.read(from: &buf), 
                userId: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: AuthStatus, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.loggedIn, into: &buf)
        FfiConverterOptionString.write(value.userId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAuthStatus_lift(_ buf: RustBuffer) throws -> AuthStatus {
    return try FfiConverterTypeAuthStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAuthStatus_lower(_ value: AuthStatus) -> RustBuffer {
    return FfiConverterTypeAuthStatus.lower(value)
}


public struct Session: Equatable, Hashable {
    /**
     * Stringified UUID for the authenticated user.
     */
    public var userId: String
    /**
     * `OpenSecret` refresh token. The Swift consumer is expected to persist
     * this in the iOS Keychain and reload it on subsequent app launches via
     * `AgicashWallet::set_session`.
     */
    public var refreshToken: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Stringified UUID for the authenticated user.
         */userId: String, 
        /**
         * `OpenSecret` refresh token. The Swift consumer is expected to persist
         * this in the iOS Keychain and reload it on subsequent app launches via
         * `AgicashWallet::set_session`.
         */refreshToken: String) {
        self.userId = userId
        self.refreshToken = refreshToken
    }

    
}

#if compiler(>=6)
extension Session: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSession: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Session {
        return
            try Session(
                userId: FfiConverterString.read(from: &buf), 
                refreshToken: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Session, into buf: inout [UInt8]) {
        FfiConverterString.write(value.userId, into: &buf)
        FfiConverterString.write(value.refreshToken, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSession_lift(_ buf: RustBuffer) throws -> Session {
    return try FfiConverterTypeSession.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSession_lower(_ value: Session) -> RustBuffer {
    return FfiConverterTypeSession.lower(value)
}


public enum FfiError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    /**
     * Auth-layer error (`OpenSecret` or local session handling).
     */
    case Auth(code: UInt32, message: String
    )
    /**
     * Storage-layer error (Supabase REST + `postgrest`).
     */
    case Storage(code: UInt32, message: String
    )
    /**
     * Internal / programmer-error / FFI plumbing failure.
     */
    case Internal(message: String
    )

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension FfiError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiError: FfiConverterRustBuffer {
    typealias SwiftType = FfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Auth(
            code: try FfiConverterUInt32.read(from: &buf), 
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .Storage(
            code: try FfiConverterUInt32.read(from: &buf), 
            message: try FfiConverterString.read(from: &buf)
            )
        case 3: return .Internal(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Auth(code,message):
            writeInt(&buf, Int32(1))
            FfiConverterUInt32.write(code, into: &buf)
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Storage(code,message):
            writeInt(&buf, Int32(2))
            FfiConverterUInt32.write(code, into: &buf)
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Internal(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiError_lift(_ buf: RustBuffer) throws -> FfiError {
    return try FfiConverterTypeFfiError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiError_lower(_ value: FfiError) -> RustBuffer {
    return FfiConverterTypeFfiError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeSession: FfiConverterRustBuffer {
    typealias SwiftType = Session?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeSession.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeSession.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeAccountFfi: FfiConverterRustBuffer {
    typealias SwiftType = [AccountFfi]

    public static func write(_ value: [AccountFfi], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeAccountFfi.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [AccountFfi] {
        let len: Int32 = try readInt(&buf)
        var seq = [AccountFfi]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeAccountFfi.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_WAKE: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureAgicashFfiInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                { handle, pollResult in
                    uniffiFutureContinuationCallback(handle: handle, pollResult: pollResult)
                },
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_agicash_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_agicash_ffi_checksum_method_agicashwallet_auth_guest() != 40474) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_agicash_ffi_checksum_method_agicashwallet_auth_login() != 63237) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_agicash_ffi_checksum_method_agicashwallet_auth_logout() != 20704) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_agicash_ffi_checksum_method_agicashwallet_auth_status() != 22694) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_agicash_ffi_checksum_method_agicashwallet_get_persisted_session() != 4899) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_agicash_ffi_checksum_method_agicashwallet_list_accounts() != 8926) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_agicash_ffi_checksum_method_agicashwallet_set_session() != 35776) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_agicash_ffi_checksum_constructor_agicashwallet_new() != 44726) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureAgicashFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all