# see https://github.com/cashubtc/cdk/blob/main/crates/cdk-mintd/example.config.toml for more options

[info]
url = "http://127.0.0.1:8085/"
listen_host = "127.0.0.1"
listen_port = 8085
mnemonic = "solar decline pole link deposit coconut region race flame truck correct yard"
enable_swagger_ui = true

[mint_management_rpc]
enabled = false

[info.http_cache]
backend = "memory"
ttl = 60
tti = 60


[info.logging]
# Where to output logs: "stdout", "file", or "both" (default: "both")
# Note: "stdout" actually outputs to stderr (standard error stream)
# output = "both"
# Log level for console output (default: "info")
# console_level = "info"  
# Log level for file output (default: "debug")
# file_level = "debug"

[mint_info]
name = "Agicash local mint"
description = "Local development mint for testing!"
description_long = ""
motd = ""

[database]
engine = "sqlite"

[ln]
ln_backend = "fakewallet"
min_mint = 1
max_mint = 500000
min_melt = 1
max_melt = 500000

[fake_wallet]
supported_units = ["sat"]
fee_percent = 0.02
reserve_fee_min = 1
min_delay_time = 1
max_delay_time = 3

[auth]
auth_enabled = true
openid_discovery = "http://127.0.0.1:8080/realms/cdk-test-realm/.well-known/openid-configuration"
openid_client_id = "cashu-client"
mint_max_bat=50

# Authentication settings for endpoints
# Options: "clear", "blind", "none" (none = disabled)
mint = "clear"
get_mint_quote = "none"  
check_mint_quote = "none"

melt = "none"
get_melt_quote = "none"
check_melt_quote = "none"

swap = "blind"
restore = "blind"
check_proof_state = "none"

