name: 'Setup Environment'
description: 'Sets up Boardwalk development environment'
runs:
  using: composite
  steps:
    - name: Install Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.1.42

    - name: Install Dependencies
      shell: bash
      run: bun install --frozen-lockfile
