name: 'Setup Environment (CI)'
description: 'Lightweight setup for CI jobs. Installs only bun and dependencies. Use setup-devenv for the full Nix development environment.'
runs:
  using: composite
  steps:
    - name: Install Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.3.8

    - name: Install Dependencies
      shell: bash
      run: bun install --frozen-lockfile
