/**
 * `@agicash/db-types` — the GENERATED Supabase types for the `wallet` schema,
 * shared by the web app and `@agicash/wallet-sdk`.
 *
 * `database.types.ts` is regenerated by the root `db:generate-types` script
 * (`supabase gen types typescript --local --schema wallet`) — do not hand-edit it.
 *
 * `Json` is defined HERE (a trivial recursive generic) rather than re-exported
 * from the generated file, so consumers import it from this package and it is
 * stable across regenerations.
 *
 * @module
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type {
  CompositeTypes,
  Database,
  Enums,
  Tables,
  TablesInsert,
  TablesUpdate,
} from './database.types';
export { Constants } from './database.types';
