// First import to initialize Sentry as soon as possible
import { sentryInstrumentation } from './instrument.server';

import { PassThrough } from 'node:stream';
import { createReadableStreamFromReadable } from '@react-router/node';
import * as Sentry from '@sentry/react-router';
import {
  getMetaTagTransformer,
  wrapSentryHandleRequest,
} from '@sentry/react-router';
import { isbot } from 'isbot';
import type { RenderToPipeableStreamOptions } from 'react-dom/server';
import { renderToPipeableStream } from 'react-dom/server';
import type { EntryContext, RouterContextProvider } from 'react-router';
import { ServerRouter } from 'react-router';
import { PRERENDERED_PATHS } from './prerender-paths';

export const streamTimeout = 5_000;

export const unstable_instrumentations = [sentryInstrumentation];

function handleRequest(
  request: Request,
  responseStatusCode: number,
  responseHeaders: Headers,
  routerContext: EntryContext,
  // If middleware is not enabled the type should be AppLoadContext
  // biome-ignore lint/correctness/noUnusedVariables: file generated by react router by running `bunx react-router reveal`
  loadContext: RouterContextProvider,
) {
  return new Promise((resolve, reject) => {
    let shellRendered = false;
    const userAgent = request.headers.get('user-agent');

    // react-router's prerender constructs requests with no user-agent header.
    const isBuildTimePrerender = !userAgent;

    // Vercel currently doesn't serve prerendered HTML as static files when
    // ssr:true (remix-run/react-router#14281) — requests for these paths
    // fall through to the SSR function. Match them here so the outlining
    // override below applies at runtime SSR too. Once the upstream adapter
    // bug is fixed, this path-list check can be dropped; the no-UA check
    // alone will cover real prerender invocations.
    const pathname = new URL(request.url).pathname.replace(/\/+$/, '') || '/';
    const isPrerenderRoute = PRERENDERED_PATHS.includes(pathname);

    const shouldDisableOutlining = isBuildTimePrerender || isPrerenderRoute;

    // Ensure requests from bots and SPA Mode renders wait for all content to load before responding
    // https://react.dev/reference/react-dom/server/renderToPipeableStream#waiting-for-all-content-to-load-for-crawlers-and-static-generation
    const readyOption: keyof RenderToPipeableStreamOptions =
      (userAgent && isbot(userAgent)) || routerContext.isSpaMode
        ? 'onAllReady'
        : 'onShellReady';

    const { pipe, abort } = renderToPipeableStream(
      <ServerRouter context={routerContext} url={request.url} />,
      {
        // React's streaming SSR uses progressiveChunkSize (default 12.8 KB) to
        // optimize first paint: when the rendered HTML exceeds this threshold,
        // React "outlines" the next Suspense boundary — it writes the fallback
        // into the initial shell and emits the actual content later as a
        // hidden <template> that an inline <script> swaps in. The server
        // flushes the shell immediately and streams the rest, so the browser
        // starts painting (with the fallback) before the full response is
        // ready.
        //
        // This trades a fallback flash for faster first paint. It's a real
        // win for streaming SSR with slow data — a skeleton beats a blank
        // page. But for prerender-eligible routes it's pure cost: when
        // served as static (the intent), the file is buffered and there's
        // no opportunity for early flushing — the fallback-then-swap dance
        // still happens in the file, so the user sees a fallback flash on
        // first paint with nothing gained. When falling through to runtime
        // SSR (current Vercel behavior, see above), the same flash returns
        // for a different reason but the same fix applies. Setting an
        // effectively-infinite threshold disables outlining for these
        // requests, so the content renders inline in the shell.
        progressiveChunkSize: shouldDisableOutlining
          ? Number.POSITIVE_INFINITY
          : undefined,
        [readyOption]() {
          shellRendered = true;
          const body = new PassThrough();
          const stream = createReadableStreamFromReadable(body);

          responseHeaders.set('Content-Type', 'text/html');

          resolve(
            new Response(stream, {
              headers: responseHeaders,
              status: responseStatusCode,
            }),
          );

          pipe(getMetaTagTransformer(body));
        },
        onShellError(error: unknown) {
          reject(error);
        },
        onError(error: unknown) {
          // biome-ignore lint/style/noParameterAssign: file generated by react router by running `bunx react-router reveal`
          responseStatusCode = 500;
          // Log streaming rendering errors from inside the shell.  Don't log
          // errors encountered during initial shell rendering since they'll
          // reject and get logged in handleDocumentRequest.
          if (shellRendered) {
            console.error(error);
          }
        },
      },
    );

    // Abort the rendering stream after the `streamTimeout` so it has time to
    // flush down the rejected boundaries
    setTimeout(abort, streamTimeout + 1000);
  });
}

// wrapSentryHandleRequest doesn't take into account the possibility of middlware being enabled so has loadContext type defined as AppLoadContext.
// However it only passes the loadContext to handleRequest so doesn't really matter. We can just ignore the type error.
// See the source code for wrapSentryHandleRequest here: https://github.com/getsentry/sentry-javascript/blob/10.5.0/packages/react-router/src/server/wrapSentryHandleRequest.ts
// biome-ignore lint/suspicious/noExplicitAny: see comment above
export default wrapSentryHandleRequest(handleRequest as any);

export const handleError = Sentry.createSentryHandleError({
  logErrors: !Sentry.isEnabled(),
});
