export {
  type AccountType,
  type AccountPurpose,
  type Account,
  type ExtendedAccount,
  type CashuAccount,
  type SparkAccount,
  type ExtendedCashuAccount,
  type ExtendedSparkAccount,
  type RedactedAccount,
  type RedactedCashuAccount,
  canSendToLightning,
  canReceiveFromLightning,
  getAccountBalance,
} from '@agicash/core/features/accounts/account';
