import type { MintBlocklist } from './internal/cashu/mint-validation';

/** Minimal async key/value store the host provides. Web = localStorage-backed,
 * node = fs/sqlite-backed. Holds session tokens (and guest credentials) only —
 * never seeds or derived keys. */
export interface StorageAdapter {
  get(key: string): Promise<string | undefined>;
  set(key: string, value: string): Promise<void>;
  remove(key: string): Promise<void>;
}

export type SdkConfig = {
  openSecret: { url: string; clientId: string };
  supabase: { url: string; anonKey: string; serviceRoleKey?: string };
  breezApiKey?: string;
  /** Writable directory for the Breez SDK's local state. Web/browser ignores it
   * (in-memory/IndexedDB); headless node needs a real path. Default './.spark-data'. */
  sparkStorageDir?: string;
  /** Durable store: auth tokens + guest credentials. Web = localStorage, node = fs/sqlite. */
  storage: StorageAdapter;
  /** Optional ephemeral store for Open Secret's enclave handshake material
   * (sessionKey/sessionId). Web passes a window.sessionStorage-backed adapter so
   * it survives reloads; headless omits it (SDK uses an in-memory store dropped
   * on dispose). */
  sessionStorage?: StorageAdapter;
  /** Leader-election instance id; autogenerated if omitted (used in later plans). */
  clientId?: string;
  /** LN-address domain for contact composition (used in later plans). If
   * omitted, ContactRepository composes lud16 addresses as `username@` (invalid),
   * so any host that uses contacts must set this. */
  domain?: string;
  /** Seed dev/test default accounts (testnut mints) on user creation. */
  includeTestAccounts?: boolean;
  /**
   * Mint URL + unit combinations to block when validating an unknown source
   * mint during a token claim. The host parses this (e.g. from
   * `VITE_CASHU_MINT_BLOCKLIST`); the SDK reads no env. Defaults to `[]`.
   */
  cashuMintBlocklist?: MintBlocklist;
};
