[info]
url = "http://127.0.0.1:8085"
listen_host = "127.0.0.1"
listen_port = 8085
# input_fee_ppk = 0
# enable_swagger_ui = false
mnemonic = "atom,atom,atom,atom,atom,atom,atom,atom,atom,atom,atom,atom,atom,atom,atom,atom,atom,atom,atom,atom,atom,atom,atom,atom,atom,atom,atom,atom,atom,atom,atom,atom"



[mint_info]
# name = "test mint"
# Hex pubkey of mint
# pubkey = ""
# description = "These are not real sats for testing only"
# description_long = "A longer mint for testing"
# motd = "Hello world"
# icon_url = "https://this-is-a-mint-icon-url.com/icon.png"
# contact_email = "hello@cashu.me"
# Nostr pubkey of mint (Hex)
# contact_nostr_public_key = ""


[database]
# Database engine (sqlite/redb) defaults to sqlite
# engine = "sqlite"

[ln]
# Required ln backend `cln`, `lnd`, `strike`, `fakewallet`, 'lnbits', 'phoenixd'
ln_backend = "cln"
# For 'phoenixd' backend, also specify fee_percent (% fee of the ln payment that mint will put in the melt quote) and reserve_fee_min (absolute amount-higher of fee_percent or reserve_fee_min is the fee reserve). 
# fee_percent=0.04
# reserve_fee_min=4

# [cln]
# Required if using cln backend path to rpc
# cln_path = ""

# [fake_wallet]
# supported_units = ["sat"]
# fee_percent = 0.02
# reserve_fee_min = 1
# min_delay_time = 1
# max_delay_time = 3