name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.1.42

    - name: Install dependencies
      run: bun install --frozen-lockfile

    - name: Install Playwright Browsers
      run: bunx playwright install --with-deps

    - name: Run Playwright tests
      run: bun run test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
