name: Preview Deployment

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
            version: 2.6.8

      - name: Testing
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID }}
        run: supabase branches list --experimental --project-ref $SUPABASE_PROJECT_ID

      # Get connection details for the automatically created branch
      - name: Get Supabase Branch Connection Details
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID }}
        run: |
          # Get branch name from PR
          BRANCH_NAME="${GITHUB_HEAD_REF}"
          BRANCH_ID=$(supabase branches list --experimental --project-ref $SUPABASE_PROJECT_ID | sed -n "s/.*\([0-9a-f]\{8\}-[0-9a-f]\{4\}-[0-9a-f]\{4\}-[0-9a-f]\{4\}-[0-9a-f]\{12\}\).*$BRANCH_NAME.*/\1/p")
          
          # Extract and set connection details as environment variables
          echo "BRANCH NAME: $BRANCH_NAME"
          echo "BRANCH_ID: $BRANCH_ID"
          supabase branches get $BRANCH_ID --project-ref $SUPABASE_PROJECT_ID --experimental --output json
        #   echo "SUPABASE_URL=$(echo $BRANCH_CONFIG | jq -r '.url')" >> $GITHUB_ENV
        #   echo "SUPABASE_ANON_KEY=$(echo $BRANCH_CONFIG | jq -r '.anon_key')" >> $GITHUB_ENV