name: Bun Pipeline

on:
  pull_request:

jobs:
  code-checks:
    name: "Format, Lint, and Types Check"
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: .github/actions/setup-environment

      - name: Run Format, Lint, and Types Check
        run: bun run check-all

  unit-tests:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: .github/actions/setup-environment

      - name: Run Unit Tests
        run: bun test

  e2e-tests:
    name: "E2E Tests"
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: .github/actions/setup-environment

      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps

      - name: Run E2E Tests
        run: bun run test:e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30