/**
 * Leader election timer loop — Slice 5 / PR7 (background).
 *
 * EXTRACTED (re-housed framework-free) from
 * `apps/web-wallet/app/features/wallet/task-processing.ts#useTakeTaskProcessingLead`. Master
 * expresses the lead poll as a `useQuery({ queryFn: takeLead, refetchInterval: 5000 })` with a
 * `useState(() => crypto.randomUUID())` client id; the framework-free SDK replaces it with a plain
 * `setInterval` timer loop over the lifted {@link TaskProcessingLockRepository}, using the SDK's
 * configured `clientId` (auto-generated by `Sdk.create` if the caller omitted one — §1). No
 * pluggable strategy (§10).
 *
 * It owns ONLY the polling + the lead/follow transition signalling. It is leadership-agnostic about
 * what the leader DOES — the {@link BackgroundProcessor} subscribes to {@link onChange} and starts /
 * stops the orchestrators + realtime processing on each transition. This keeps the lock mechanism
 * (master's `take_lead` RPC) cleanly separated from the work it gates.
 *
 * Master verbatim semantics preserved: poll every {@link POLL_INTERVAL_MS} ms; a failed poll is
 * logged and retried on the next tick (NOT treated as losing the lead — a transient DB blip must
 * not flap the processor); the first poll runs immediately on {@link start} (master's `useQuery`
 * fires at once, then on the interval).
 *
 * @module
 */
import type { TaskProcessingLockRepository } from './task-processing-lock-repository';

/** The lead poll interval (master's `refetchInterval: 5000`). */
export const POLL_INTERVAL_MS = 5000;

/** Whether this instance currently holds the processing lead. */
export type LeadStatus = 'leader' | 'follower';

/** Collaborators the loop needs. */
export type LeaderElectionDeps = {
  /** The lifted `take_lead` lock repository. */
  lockRepository: TaskProcessingLockRepository;
  /** This instance's leader-election client id (from `SdkConfig.clientId`, auto-generated if omitted). */
  clientId: string;
  /** Resolve the current signed-in user's id (the lock is per-user). Returns null when signed out. */
  getUserId: () => Promise<string | null>;
  /** Called on every LEAD/FOLLOW transition (not on each poll — only when the status flips). */
  onChange: (status: LeadStatus) => void;
};

/**
 * Polls `take_lead` on an interval and reports lead/follow transitions. Framework-free; one
 * instance per SDK, owned by {@link BackgroundProcessor}.
 */
export class LeaderElection {
  /** The running interval handle, or null when stopped. */
  private timer: ReturnType<typeof setInterval> | null = null;
  /** Aborts an in-flight `take_lead` request on {@link stop}. */
  private abortController: AbortController | null = null;
  /** The last reported status (so {@link onChange} fires only on a flip). null = not yet known. */
  private status: LeadStatus | null = null;
  /** Guards against overlapping polls if one `take_lead` outlives the interval. */
  private polling = false;

  constructor(private readonly deps: LeaderElectionDeps) {}

  /**
   * Start polling. Runs the first poll immediately (matching master's `useQuery`), then every
   * {@link POLL_INTERVAL_MS} ms. Idempotent — calling `start` while already running is a no-op.
   */
  start(): void {
    if (this.timer !== null) {
      return;
    }
    this.timer = setInterval(() => {
      void this.pollOnce();
    }, POLL_INTERVAL_MS);
    // Master's useQuery fires at once, then on the interval — run an immediate first poll.
    void this.pollOnce();
  }

  /**
   * Stop polling: clear the timer, abort any in-flight `take_lead`, and reset the known status so
   * a later {@link start} re-reports the first transition. Does NOT itself yield the DB lock — the
   * lock simply expires (its heartbeat stops being renewed) and another client takes over.
   */
  stop(): void {
    if (this.timer !== null) {
      clearInterval(this.timer);
      this.timer = null;
    }
    this.abortController?.abort();
    this.abortController = null;
    this.status = null;
  }

  /** The current known lead status (or `'follower'` before the first successful poll). */
  current(): LeadStatus {
    return this.status ?? 'follower';
  }

  /**
   * Run a SINGLE lead poll: resolve the user id, attempt `take_lead`, and fire {@link onChange} iff
   * the status flipped. A poll while signed out (no user id) reports `follower`. A failed poll is
   * logged and left for the next tick — it does NOT change the reported status (a transient DB blip
   * must not flap the leader). The interval calls this; tests pump it directly (no real timer).
   * Overlapping calls are guarded (a poll outliving the interval will not re-enter).
   */
  async pollOnce(): Promise<void> {
    if (this.polling) {
      return;
    }
    this.polling = true;
    const abortController = new AbortController();
    this.abortController = abortController;
    try {
      const userId = await this.deps.getUserId();
      if (!userId) {
        this.report('follower');
        return;
      }
      const isLeader = await this.deps.lockRepository.takeLead(
        userId,
        this.deps.clientId,
        { abortSignal: abortController.signal },
      );
      this.report(isLeader ? 'leader' : 'follower');
    } catch (error) {
      // Aborted by stop() — not an error worth logging.
      if (abortController.signal.aborted) {
        return;
      }
      console.warn('Take lead request failed. Will retry in 5 seconds.', {
        cause: error,
      });
    } finally {
      if (this.abortController === abortController) {
        this.abortController = null;
      }
      this.polling = false;
    }
  }

  /** Report `status`, invoking `onChange` only when it differs from the last reported value. */
  private report(status: LeadStatus): void {
    if (this.status === status) {
      return;
    }
    this.status = status;
    this.deps.onChange(status);
  }
}
